name: asl-recognition
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip=21.2.4
  - pip:
    - tensorflow==2.13.0
    - keras==2.13.0
    - flask==2.0.1
    - flask-cors==3.0.10
    - numpy==1.24.3
    - scikit-learn==1.0.2
    - matplotlib==3.5.1
    - pandas==1.4.2
    - python-dotenv==0.19.2
    - requests==2.27.1
    - pillow==9.0.1
    - h5py==3.6.0 